package net.mips.compiler;

public enum Tokens {
    ID_TOKEN, NUM_TOKEN, PLUS_TOKEN, MOINS_TOKEN, MUL_TOKEN,
    DIV_TOKEN, EG_TOKEN, DIFF_TOKEN, INF_TOKEN, SUP_TOKEN,
    INFEG_TOKEN, SUPEG_TOKEN, PARG_TOKEN, PARD_TOKEN, VIR_TOKEN,
    PVIR_TOKEN, PNT_TOKEN, AFFEC_TOKEN, BEGIN_TOKEN, END_TOKEN,
    IF_TOKEN, WHILE_TOKEN, DO_TOKEN, THEN_TOKEN, WRITE_TOKEN,
    READ_TOKEN, CONST_TOKEN, VAR_TOKEN, PROGRAM_TOKEN, ERR_TOKEN;

}
